name: clould_music
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  shared_preferences: ^0.5.3+4
  dio: ^2.1.0
  flutter_screenutil: ^0.6.0
  fluro: ^1.5.1
  fluttertoast: ^3.1.3
  common_utils: ^1.1.3
  cookie_jar: ^1.0.0
  permission_handler: ^3.2.0
  path_provider: ^1.3.0
  extended_image: ^0.6.1
  get_it: ^3.0.1
  audioplayers: ^0.13.2
  flutter_easyrefresh: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
